"""ajuste coluna tabela de transações

Revision ID: 1f2b691cd43d
Revises: bfde75fb4276
Create Date: 2025-08-25 21:59:06.006088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2b691cd43d'
down_revision: Union[str, None] = 'bfde75fb4276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('plano_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transacoes', 'planos', ['plano_id'], ['id'])
    op.drop_column('transacoes', 'pagarme_planoId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('pagarme_planoId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_column('transacoes', 'plano_id')
    # ### end Alembic commands ###
