"""adicionado coluna template_html na tabela templates

Revision ID: 40ddd2a1387e
Revises: 465953244d98
Create Date: 2025-08-28 14:48:23.852339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ddd2a1387e'
down_revision: Union[str, None] = '465953244d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'template_html')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template_html', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
