"""adicionado coluna modo na tabela de documentos

Revision ID: 5c8ffd453c4f
Revises: 977c2579e558
Create Date: 2025-08-21 11:34:02.232711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8ffd453c4f'
down_revision: Union[str, None] = '977c2579e558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('modo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'modo')
    # ### end Alembic commands ###
