"""removido coluna plano da tabela users

Revision ID: 5d25f50c692e
Revises: 964015cd4c89
Create Date: 2025-08-25 10:54:30.642592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d25f50c692e'
down_revision: Union[str, None] = '964015cd4c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plano')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plano', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
