"""cliente_id pode ser null na tabela de documentos

Revision ID: 6768bfc89a1b
Revises: 5c8ffd453c4f
Create Date: 2025-08-21 11:37:59.445251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6768bfc89a1b'
down_revision: Union[str, None] = '5c8ffd453c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos', 'cliente_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos', 'cliente_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
