"""ajuste tabela de documentos

Revision ID: 8249ce285266
Revises: 2069aa9068b8
Create Date: 2025-08-21 10:47:06.770760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8249ce285266'
down_revision: Union[str, None] = '2069aa9068b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_documento', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('documento_text', sa.TEXT(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('contratos')
    op.create_unique_constraint(None, 'clientes', ['id'])
    op.create_unique_constraint(None, 'password_reset_tokens', ['id'])
    op.create_unique_constraint(None, 'prestador', ['id'])
    op.create_unique_constraint(None, 'templates', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'templates', type_='unique')
    op.drop_constraint(None, 'prestador', type_='unique')
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.drop_constraint(None, 'clientes', type_='unique')
    op.create_table('contratos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome_contrato', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contrato_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at_cliente', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at_cliente', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='contratos_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name='contratos_template_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='contratos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contratos_pkey')
    )
    op.drop_table('documentos')
    # ### end Alembic commands ###
