"""ajuste tabela de prestador

Revision ID: 940b1fb2715d
Revises: 1f2b691cd43d
Create Date: 2025-08-27 22:37:42.673608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940b1fb2715d'
down_revision: Union[str, None] = '1f2b691cd43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prestador', 'tipo_prestador',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('prestador', 'telefone_prestador',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('prestador', 'email_prestador',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prestador', 'email_prestador',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prestador', 'telefone_prestador',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prestador', 'tipo_prestador',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
