"""adicionado coluna modo na tabela de documentos

Revision ID: 977c2579e558
Revises: 8249ce285266
Create Date: 2025-08-21 11:30:10.345085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977c2579e558'
down_revision: Union[str, None] = '8249ce285266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documentos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos', type_='unique')
    # ### end Alembic commands ###
