"""criação das novas tabelas

Revision ID: 9fc8f860812e
Revises: afc6a4c89e43
Create Date: 2025-08-22 19:06:41.369314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc8f860812e'
down_revision: Union[str, None] = 'afc6a4c89e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('tipo_desconto', sa.String(), nullable=False),
    sa.Column('valor_desconto', sa.Integer(), nullable=False),
    sa.Column('aplicavel', sa.String(), nullable=False),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('limit_uso_usuario', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('termino', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('planos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('preco_cents', sa.Integer(), nullable=False),
    sa.Column('ciclo_faturamento', sa.String(), nullable=False),
    sa.Column('pagarme_planoId', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cupom_usado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cupom_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_usado', sa.Integer(), nullable=False),
    sa.Column('ultima_vez_usado', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_transacao', sa.String(), nullable=False),
    sa.Column('valor_cents', sa.Integer(), nullable=False),
    sa.Column('pagarme_transacao_id', sa.String(), nullable=False),
    sa.Column('pagarme_planoId', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('inicio_plano', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('fim_plano', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('assinatura_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('plano_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'planos', ['plano_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'plano_id')
    op.drop_column('users', 'assinatura_id')
    op.drop_column('users', 'fim_plano')
    op.drop_column('users', 'inicio_plano')
    op.drop_table('transacoes')
    op.drop_table('cupom_usado')
    op.drop_table('planos')
    op.drop_table('cupons')
    # ### end Alembic commands ###
