"""adicionado coluna template_html na tabela templates

Revision ID: a4e32f2caadb
Revises: 940b1fb2715d
Create Date: 2025-08-28 12:01:07.396131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e32f2caadb'
down_revision: Union[str, None] = '940b1fb2715d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template_html', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'template_html')
    # ### end Alembic commands ###
