"""adicionado coluna de cupom na tabela de transações

Revision ID: bfde75fb4276
Revises: d321dcb6e02b
Create Date: 2025-08-25 21:48:52.431023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfde75fb4276'
down_revision: Union[str, None] = 'd321dcb6e02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('cupom_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transacoes', 'cupons', ['cupom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_column('transacoes', 'cupom_id')
    # ### end Alembic commands ###
