"""ajuste coluna plano_id tabela users

Revision ID: d321dcb6e02b
Revises: 5d25f50c692e
Create Date: 2025-08-25 11:17:20.007975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd321dcb6e02b'
down_revision: Union[str, None] = '5d25f50c692e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plano_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plano_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
