"""adicionado coluna template_html na tabela templates

Revision ID: e332d04c76e6
Revises: 40ddd2a1387e
Create Date: 2025-08-29 12:05:42.921576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e332d04c76e6'
down_revision: Union[str, None] = '40ddd2a1387e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template_url', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('template_html', sa.String(), nullable=True))
    op.drop_column('templates', 'template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('templates', 'template_html')
    op.drop_column('templates', 'template_url')
    # ### end Alembic commands ###
